name: Build and Upload Executable

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Build executable with PyInstaller
      - name: Build executable
        run: |
          pip install pyinstaller
          pyinstaller --onefile --noconsole brightness_control.py

      # Upload the built .exe file as an artifact
      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: brightness_control_exe
          path: dist/brightness_control.exe
