name: Build and Release Executable

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Build the executable
      - name: Build executable
        run: |
          pip install pyinstaller
          pyinstaller --onefile --noconsole brightness_control.py

      # Upload files to release
      - name: Create Release and Upload Files
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v1.3.6
          name: "AutoBrightnessControl v1.3.6"
          body: "The main change in version 1.3.x was adaptive brightness change depending on the content on the screen. I understand that not everyone needs such a feature, that's why there is an argument --adj."
          draft: false
          prerelease: false
          artifacts: |
            dist/brightness_control.exe
            brightness_control.py
            create_task.bat
